# Generated by Django 5.2.10 on 2026-02-01 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentdrive_assessment_instructions_and_more'),
        ('users', '0013_alter_memberprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='recruitment/assignments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='recruitment.recruitmentdrive')),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_assignments', to='users.sig')),
            ],
        ),
    ]
