# Generated by Django 5.2.10 on 2026-02-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentdrive_assessment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='assessment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='interview_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='interview_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='oa_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='solution_link',
            field=models.URLField(blank=True, help_text='Link to hosted solution (Drive/GitHub)'),
        ),
        migrations.AddField(
            model_name='recruitmentassignment',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to external assignment doc/folder'),
        ),
    ]
