# Generated by Django 5.2.10 on 2026-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_role_can_manage_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='sigs',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.sig'),
        ),
    ]
