# Generated by Django 5.2.10 on 2026-01-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_memberprofile_sigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_content',
            field=models.BooleanField(default=False),
        ),
    ]
