# Generated by Django 5.2.10 on 2026-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_form_closes_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='theme',
            field=models.CharField(choices=[('cyberpunk', 'Cyberpunk Neon'), ('minimal', 'Minimalist Glass'), ('industrial', 'Industrial Steel'), ('academic', 'Academic Official'), ('solaris', 'Solaris Vivid'), ('midnight', 'Midnight Indigo')], default='cyberpunk', max_length=30),
        ),
    ]
