# Generated by Django 5.2.10 on 2026-01-27 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_form_theme'),
        ('events', '0002_event_due_date_event_is_full_event_event_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='events.event'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
