# Generated by Django 5.2.10 on 2026-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_galleryimage_event_galleryimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='success_link',
            field=models.URLField(blank=True, help_text='Optional link to redirect to or show after submission'),
        ),
        migrations.AddField(
            model_name='form',
            name='success_link_label',
            field=models.CharField(blank=True, default='Continue', help_text='Label for the success link button', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='success_message',
            field=models.TextField(blank=True, default='Your response has been integrated. Session terminates now.'),
        ),
    ]
