# Generated by Django 5.2.10 on 2026-01-27 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0012_role_can_manage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_full_event',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('SIG', 'SIG Specific'), ('PERSONAL', 'Personal')], default='GLOBAL', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='sig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.sig'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Event Date'),
        ),
    ]
